/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Starting;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import javax.swing.ButtonGroup;
import static javax.swing.GroupLayout.Alignment.CENTER;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author DataByte_Logics
 */
public class ChooseAnalysis extends javax.swing.JFrame {

    /**
     * Creates new form ChooseAnalysis1
     */
    public ChooseAnalysis() {
        initComponents();
        getContentPane().setBackground(new Color(197,226,252));
        //getContentPane().setBackground(Color.white);
        setForeground(Color.BLACK);
       
        ButtonGroup b=new ButtonGroup();
        b.add(arch);
        b.add(struct);
       this.setLocationRelativeTo(null);
        this.setLayout();
         setIconImage(Toolkit.getDefaultToolkit().getImage("icons/type.png"));
    }
public void setLayout(){
    this.setLayout(new BorderLayout());
	//JLabel background=new JLabel(new ImageIcon("D:\\Nishant Wok\\Projects\\Scrutinizer\\src\\box.jpg"));
	//add(background);
	//background.setLayout(new FlowLayout());
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arch = new javax.swing.JRadioButton();
        struct = new javax.swing.JRadioButton();
        btnexit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Domain Chooser");
        setBackground(new java.awt.Color(255, 153, 153));
        setBounds(new java.awt.Rectangle(300, 200, 0, 0));
        setResizable(false);

        arch.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        arch.setText("Architectural Domain");
        arch.setOpaque(false);
        arch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                archItemStateChanged(evt);
            }
        });
        arch.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                archStateChanged(evt);
            }
        });
        arch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archActionPerformed(evt);
            }
        });

        struct.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        struct.setText("Structural Domain");
        struct.setOpaque(false);
        struct.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                structItemStateChanged(evt);
            }
        });
        struct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                structActionPerformed(evt);
            }
        });

        btnexit.setBackground(new java.awt.Color(255, 255, 255));
        btnexit.setFont(new java.awt.Font("Yu Mincho Light", 0, 18)); // NOI18N
        btnexit.setForeground(new java.awt.Color(0, 51, 204));
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("3D MODEL CHECKER");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arch, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(struct)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(arch, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(struct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnexit)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void archStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_archStateChanged
       
    }//GEN-LAST:event_archStateChanged

    private void archItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_archItemStateChanged
 if(arch.isEnabled()==true)
        {
            ChooseIfcArch i=new ChooseIfcArch();
            i.setVisible(true);
            this.setVisible(false);
        }        
// TODO add your handling code here:
    }//GEN-LAST:event_archItemStateChanged

    private void structItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_structItemStateChanged
if(struct.isEnabled()==true)
        {
            
            MainDesktopStruct mainWindow=new MainDesktopStruct();
            this.setVisible(false);
            mainWindow.setVisible(true);
        }     
        // TODO add your handling code here:
    }//GEN-LAST:event_structItemStateChanged

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed

        if(JOptionPane.showConfirmDialog(this,"Do u Want to Exit this Application")==JOptionPane.OK_OPTION)
        {
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnexitActionPerformed

    private void archActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_archActionPerformed

    private void structActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_structActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_structActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton arch;
    private javax.swing.JButton btnexit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton struct;
    // End of variables declaration//GEN-END:variables
}
