/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Starting;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.nio.file.FileSystems;
import java.nio.file.Path;
import java.sql.Array;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Timestamp;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javax.swing.DefaultListModel;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import luck.Connect;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;


/**
 *
 * @author DataByte Logics
 */


public class Validation extends javax.swing.JInternalFrame {

    public class Item {

    private Float Position;
    private String Name;

    public Item(Float position, String name) {
        this.Position = position;
        this.Name = name;
    }

    public Float getPosiFloat() {
        return Position;
    }

    public void setPosition(Float position) {
        this.Position = position;
    }

    public String getName() {
        return Name;
    }

    public void setName(String name) {
        this.Name = name;
    }

    public String toString(){
        return this.Name;
    }
}
    /**
     * Creates new form Validation
     */
    JList<Item> stories=new JList<Item>();
    String FileId="";
    String Path="";
    ResultSet rs;
    ResultSet Seprs;
    ResultSetMetaData mt;
    Structural_Analysis.Connect c=new Structural_Analysis.Connect();
    DefaultListModel<Item>  listModel = new DefaultListModel<Item>();
    DefaultListModel<String>  singlelinewalls = new DefaultListModel<String>();
    DefaultListModel<String>  jointwalls = new DefaultListModel<String>();

    public Validation() {
        initComponents();
        getContentPane().setBackground(new Color(197,226,252));
        Preferences userPreferences = Preferences.userRoot();
        FileId = userPreferences.get("fileid","0");      
        c.getStorey(FileId);
        try
        {
        rs=c.DqlStatement();
       
                while(rs.next()!=false)
                        {
                           listModel.addElement(new Item(rs.getFloat("Position"), rs.getString("LevelName")));
                            drpStorey.addItem(rs.getString("LevelName"));
                        }
                stories = new JList(listModel);
                 String g="";
            
      
        }
        catch(Exception ex)
        {
             String g="";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        validationlabel = new javax.swing.JLabel();
        drpCheck = new javax.swing.JComboBox();
        validatebutton = new javax.swing.JButton();
        status = new javax.swing.JLabel();
        btnexit1 = new javax.swing.JButton();
        txtStorey = new javax.swing.JLabel();
        drpStorey = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(197, 226, 252));
        setClosable(true);
        setIconifiable(true);
        setTitle("Validation");

        validationlabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        validationlabel.setText("Validation");

        drpCheck.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        drpCheck.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Any Check", "Effective Height of Wall", "Effective Length of Wall", "Effective Thichness of Wall", "Selenderness Ratio" }));
        drpCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                drpCheckItemStateChanged(evt);
            }
        });
        drpCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drpCheckActionPerformed(evt);
            }
        });

        validatebutton.setBackground(new java.awt.Color(102, 102, 102));
        validatebutton.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        validatebutton.setForeground(new java.awt.Color(0, 51, 204));
        validatebutton.setText("Validate");
        validatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validatebuttonActionPerformed(evt);
            }
        });

        status.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        status.setText("Status : Check Not Selected");
        status.setToolTipText("");

        btnexit1.setBackground(new java.awt.Color(102, 102, 102));
        btnexit1.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnexit1.setForeground(new java.awt.Color(0, 51, 204));
        btnexit1.setText("Close");
        btnexit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexit1ActionPerformed(evt);
            }
        });

        txtStorey.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtStorey.setText("Storey");

        drpStorey.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        drpStorey.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a Storey" }));
        drpStorey.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                drpStoreyItemStateChanged(evt);
            }
        });
        drpStorey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drpStoreyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtStorey, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(validationlabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drpCheck, 0, 438, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(validatebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnexit1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(drpStorey, javax.swing.GroupLayout.Alignment.TRAILING, 0, 438, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validationlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drpCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStorey, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drpStorey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validatebutton)
                    .addComponent(btnexit1))
                .addGap(18, 18, 18)
                .addComponent(status)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void drpCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_drpCheckItemStateChanged
        if(drpCheck.getSelectedIndex()==0)
        {
            status.setText("Status : Check not Selected");
        }
        else
        {
            if(drpStorey.getSelectedIndex()==0)
            {
                status.setText("Status : Storey not Selected");
            }
            else
            {
                status.setText("Status : Press Validate Button to proceed");
            }
             
        }
    }//GEN-LAST:event_drpCheckItemStateChanged

    private void validatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validatebuttonActionPerformed
       validatebutton.setEnabled(false);
       try
       {
        if(drpCheck.getSelectedIndex()==1)
        {
            
		XSSFWorkbook workbook = new XSSFWorkbook ();
		XSSFSheet sheet = workbook.createSheet();
                
                //Create First Row
		XSSFRow row1 = sheet.createRow(0);
		XSSFCell r1c1 = row1.createCell(0);
		r1c1.setCellValue("Entity");
		XSSFCell r1c2 = row1.createCell(1);
		r1c2.setCellValue("GlobalId");
                XSSFCell r1c12 = row1.createCell(2);
		r1c12.setCellValue("Name");
		XSSFCell r1c3 = row1.createCell(3);
		r1c3.setCellValue("Storey");
                XSSFCell r1c4 = row1.createCell(4);
		r1c4.setCellValue("Height");
                XSSFCell r1c5 = row1.createCell(5);
		r1c5.setCellValue("Length");
                XSSFCell r1c6 = row1.createCell(6);
		r1c6.setCellValue("Thickness");
                XSSFCell r1c7 = row1.createCell(7);
		r1c7.setCellValue("No. Of Openings");
                XSSFCell r1c8 = row1.createCell(8);
		r1c8.setCellValue("Height of Biggest Opening");
                XSSFCell r1c9 = row1.createCell(9);
		r1c9.setCellValue("Calculated Height");
                XSSFCell r1c10 = row1.createCell(10);
		r1c10.setCellValue("Effective Height");
                XSSFCell r1c11 = row1.createCell(11);
		r1c11.setCellValue("Formula");
                
                   try {
                      for(int i=0;i<listModel.size();i++)
                      {
                           //Create First Row
                          
                          
                          Item item=listModel.getElementAt(i);
                          String Val=(String)drpStorey.getSelectedItem();
                          String DVal=item.getName();
                          if(DVal.equals(Val))
                          {
                              c.getLowerSlab(item.getPosiFloat(),FileId);
                              rs=c.DqlStatement();
                              if(rs.next()!=false)
                              {
                                  
                                  Float Lower_Slab_Thickness=rs.getFloat("Depth");
                                  
                                  c.getUpperSlab(item.getPosiFloat(),FileId);
                                  rs=c.DqlStatement();
                                  
                                  if(rs.next()!=false)
                                  {
                                      Float Upper_Slab_Thickness=rs.getFloat("Depth");
                                      
                                      c.getWalls(item.getPosiFloat(),FileId);
                                      Seprs=c.DqlStatement();
                                      int rowcount=1;
                                      while(Seprs.next()!=false)
                                      {
                                          XSSFRow row = sheet.createRow(rowcount);
                                          
                                          XSSFCell r1c = row.createCell(0);
                                          r1c.setCellValue("Wall");
                                          Float Start=0.0f;
                                          c.getLengthOfWall(Seprs.getString("GlobalId"), FileId);
                                          ResultSet lenres=c.DqlStatement();
                                          if(lenres.next()!=false)
                                          {
                                              Float Length_Of_Wall=lenres.getFloat("Length");
                                              Float Thickness_Of_Wall=Seprs.getFloat("Thickness");
                                              
                                              r1c = row.createCell(1);
                                              r1c.setCellValue(Seprs.getString("GlobalId"));  
                                              
                                              r1c = row.createCell(2);
                                              r1c.setCellValue(Seprs.getString("Name"));  
                                              
                                              r1c = row.createCell(3);
                                              r1c.setCellValue(Val);
                                              
                                              r1c = row.createCell(4);
                                              r1c.setCellValue(Seprs.getFloat("Height"));   
                                              
                                              r1c = row.createCell(5);
                                              r1c.setCellValue(Length_Of_Wall); 
                                              
                                              r1c = row.createCell(6);
                                              r1c.setCellValue(Thickness_Of_Wall); 
                                               
                                              if(Length_Of_Wall>(4*Thickness_Of_Wall))
                                              {
                                                      if(Float.compare(item.getPosiFloat(),Start)==0)
                                                      {
                                                        Float Height=(Lower_Slab_Thickness/1000)+(Seprs.getFloat("Height")/1000)+((Upper_Slab_Thickness/1000)/2);
                                                        Double Effective_Height=0.75*Height;
                                                        
                                                        r1c = row.createCell(9);
                                                        r1c.setCellValue(Height); 
                                                        
                                                        r1c = row.createCell(10);
                                                        r1c.setCellValue(Effective_Height); 
                                                        
                                                        r1c = row.createCell(11);
                                                        r1c.setCellValue("0.75*H"); 
                                                      }
                                                      else
                                                      {
                                                        Float Height=((Lower_Slab_Thickness/1000)/2)+(Seprs.getFloat("Height")/1000)+((Upper_Slab_Thickness/1000)/2);
                                                        Double Effective_Height=0.75*Height;   
                                                        
                                                        r1c = row.createCell(9);
                                                        r1c.setCellValue(Height); 
                                                        
                                                        r1c = row.createCell(10);
                                                        r1c.setCellValue(Effective_Height); 
                                                        
                                                        r1c = row.createCell(11);
                                                        r1c.setCellValue("0.75*H"); 
                                                      }      
                                              }
                                              else
                                              {
                                                  c.getJointsOfWall(Seprs.getString("GlobalId"), FileId);
                                                  ResultSet joinres=c.DqlStatement();
                                                  if(joinres.next()!=false)
                                                  {
                                                      int Joints=joinres.getInt("Joints");
                                                      if(Joints>0)
                                                      {
                                                          if(Float.compare(item.getPosiFloat(),Start)==0)
                                                          {
                                                            Float Height=(Lower_Slab_Thickness/1000)+(Seprs.getFloat("Height")/1000)+((Upper_Slab_Thickness/1000)/2);
                                                            Double Effective_Height=0.75*Height;
 
                                                            
                                                             r1c = row.createCell(9);
                                                             r1c.setCellValue(Height); 
                                                        
                                                             r1c = row.createCell(10);
                                                             r1c.setCellValue(Effective_Height); 
                                                        
                                                             r1c = row.createCell(11);
                                                             r1c.setCellValue("0.75*H"); 
                                                          }
                                                          else
                                                          {
                                                            Float Height=((Lower_Slab_Thickness/1000)/2)+(Seprs.getFloat("Height")/1000)+((Upper_Slab_Thickness/1000)/2);
                                                            Double Effective_Height=0.75*Height;     
                                                            
                                                            
                                                            r1c = row.createCell(9);
                                                             r1c.setCellValue(Height); 
                                                        
                                                             r1c = row.createCell(10);
                                                             r1c.setCellValue(Effective_Height); 
                                                        
                                                             r1c = row.createCell(11);
                                                             r1c.setCellValue("0.75*H"); 
                                                          }
                                                      }
                                                      else
                                                      {
                                                          c.getOpeningsinWall(Seprs.getString("GlobalId"), FileId);
                                                          ResultSet openres=c.DqlStatement();
                                                          if(openres.next()!=false)
                                                          {
                                                              int Opening=openres.getInt("Openings");
                                                              if(Opening>0)
                                                              {
                                                                  c.getBiggestOpeningWall(Seprs.getString("GlobalId"), FileId);
                                                                  ResultSet opensizeres=c.DqlStatement();
                                                                  if(opensizeres.next()!=false)
                                                                  {
                                                                      Float OpeningHeight=opensizeres.getFloat("Height");
                                                                            r1c = row.createCell(7);
                                                                            r1c.setCellValue(Opening);
                                                                            
                                                                            r1c = row.createCell(8);
                                                                            r1c.setCellValue(OpeningHeight); 
                                                                            
                                                                       if(Float.compare(item.getPosiFloat(),Start)==0)
                                                                        {
                                                                            Float Height=(Lower_Slab_Thickness/1000)+(Seprs.getFloat("Height")/1000)+((Upper_Slab_Thickness/1000)/2);
                                                                            Double Effective_Height=(0.75*Height)+(0.25*OpeningHeight);
                                                                            
                                                                            r1c = row.createCell(9);
                                                                            r1c.setCellValue(Height); 
                                                        
                                                                            r1c = row.createCell(10);
                                                                            r1c.setCellValue(Effective_Height); 
                                                        
                                                                            r1c = row.createCell(11);
                                                                            r1c.setCellValue("0.75*H + 0.25*H1"); 
                                                                        }
                                                                        else
                                                                        {
                                                                            Float Height=((Lower_Slab_Thickness/1000)/2)+(Seprs.getFloat("Height")/1000)+((Upper_Slab_Thickness/1000)/2);
                                                                            Double Effective_Height=0.75*Height+(0.25*OpeningHeight); 
                                                                            
                                                                            r1c = row.createCell(9);
                                                                            r1c.setCellValue(Height); 
                                                        
                                                                            r1c = row.createCell(10);
                                                                            r1c.setCellValue(Effective_Height); 
                                                        
                                                                            r1c = row.createCell(11);
                                                                            r1c.setCellValue("0.75*H + 0.25*H1"); 
                                                                        }
                                                                  }
                                                              }
                                                              else
                                                              {
                                                                  Float Height=(Lower_Slab_Thickness/1000)+(Seprs.getFloat("Height")/1000)+((Upper_Slab_Thickness/1000)/2);
                                                                  Float Effective_Height=Height;
                                                                  
                                                                            r1c = row.createCell(9);
                                                                            r1c.setCellValue(Height); 
                                                        
                                                                            r1c = row.createCell(10);
                                                                            r1c.setCellValue(Effective_Height); 
                                                        
                                                                            r1c = row.createCell(11);
                                                                            r1c.setCellValue("H"); 
                                                              }
                                                          }
                                                      }
                                                  }
                                              }
                                            
                                          }
                                            singlelinewalls = new DefaultListModel<String>();
                                           jointwalls = new DefaultListModel<String>();
                                           rowcount++;
                                      }
                                      Timestamp timestamp = new Timestamp(System.currentTimeMillis());
                                      Path path = FileSystems.getDefault().getPath("").toAbsolutePath();
                                      File ouputfiles = new File(path+"\\IFC_Validations.xlsx");
                                      FileOutputStream out = new FileOutputStream(ouputfiles);
                                      workbook.write(out);
                                      out.close();
                                  }
                              }
                          }
                      }
                       status.setText("Status: Check Performed");
                   } catch (Exception ex) {
                       Logger.getLogger(MainWindowIfc.class.getName()).log(Level.SEVERE, null, ex);
                   }
        }
        else if(drpCheck.getSelectedIndex()==2)
        {
                   try {
                      for(int i=0;i<listModel.size();i++)
                      {
                          Item item=listModel.getElementAt(i);
                          String Val=(String)drpStorey.getSelectedItem();
                          String DVal=item.getName();
                          if(DVal.equals(Val))
                          {

                                      c.getWalls(item.getPosiFloat(),FileId);
                                      Seprs=c.DqlStatement();
                                      while(Seprs.next()!=false)
                                      {
                                          Float Start=0.0f;
                                          c.getLengthOfWall(Seprs.getString("GlobalId"), FileId);
                                          ResultSet lenres=c.DqlStatement();
                                          if(lenres.next()!=false)
                                          {
                                              Float Length_Of_Wall=lenres.getFloat("Length");
                                              Float Thickness_Of_Wall=Seprs.getFloat("Thickness");
                                              c.getSingleLineWalls(Seprs.getString("GlobalId"),item.getPosiFloat(),FileId);
                                              ResultSet singlelinewallsres=c.DqlStatement();
                                              while(singlelinewallsres.next()!=false)
                                              {
                                                  singlelinewalls.addElement(singlelinewallsres.getString("GlobalId"));
                                              }
                                              
                                              c.getConnectedWalls(Seprs.getString("GlobalId"),item.getPosiFloat(),FileId);
                                              ResultSet connectedwallres=c.DqlStatement();
                                              while(connectedwallres.next()!=false)
                                              {
                                                  jointwalls.addElement(connectedwallres.getString("GlobalId"));
                                              }
                                              int counter=0;
                                              for(int j=0;j<singlelinewalls.size();j++)
                                              {
                                                 for(int k=0;k<jointwalls.size();k++)
                                                {
                                                  if(singlelinewalls.getElementAt(j).equals(jointwalls.getElementAt(k)))
                                                  {
                                                      counter++;
                                                  }
                                                } 
                                              }
                                               c.getOpeningsinWall(Seprs.getString("GlobalId"), FileId);
                                                          ResultSet openres=c.DqlStatement();
                                                          if(openres.next()!=false)
                                                          {
                                                              int Opening=openres.getInt("Openings");
                                                              if(Opening>0)
                                                              {
                                                                 c.getBiggestOpeningWall(Seprs.getString("GlobalId"), FileId);
                                                                  ResultSet opensizeres=c.DqlStatement();
                                                                  if(opensizeres.next()!=false)
                                                                  {
                                                                      Float OpeningHeight=opensizeres.getFloat("Height");
                                                                      Float Height_Of_Wall=Seprs.getFloat("Thickness");
                                                                      if((0.5*Height_Of_Wall)<OpeningHeight)
                                                                      {
                                               
                                               if(counter==1)
                                              {
                                                  if((Thickness_Of_Wall*4)>Length_Of_Wall)
                                                  {
                                                    Float Effective_Length=2*Length_Of_Wall;
                                                  }
                                                  else
                                                  {
                                                      Double Effective_Length=1.5*Length_Of_Wall;
                                                  }
                                                  
                                              }
                                              
                                                                      }
                                                                      else
                                                                      {
                                                                       if(counter==0)
                                              {
                                                  Float EffectiveLength=Length_Of_Wall;
                                              }
                                              else if(counter==1)
                                              {
                                                  Double Effective_Length=0.9*Length_Of_Wall;
                                              }
                                              else
                                              {
                                                  Double Effective_Length=0.8*Length_Of_Wall;
                                              }   
                                                                      }
                                                                  }
                                                              }
                                                              else
                                                          {
                                              if(counter==0)
                                              {
                                                  Float EffectiveLength=Length_Of_Wall;
                                              }
                                              else if(counter==1)
                                              {
                                                  Double Effective_Length=0.9*Length_Of_Wall;
                                              }
                                              else
                                              {
                                                  Double Effective_Length=0.8*Length_Of_Wall;
                                              }
                                                          }
                                                          }
                                                          
                                            
                                          }
                                         singlelinewalls = new DefaultListModel<String>();
                                           jointwalls = new DefaultListModel<String>(); 
                                      }
                                  
                              
                          
                      }
                      }
                       status.setText("Status: Check Performed");
                   } catch (Exception ex) {
                       System.out.println(ex.toString());
                       Logger.getLogger(MainWindowIfc.class.getName()).log(Level.SEVERE, null, ex);
                   }
        }
        else if (drpCheck.getSelectedIndex()==3)
        {
                  
        }
        else if(drpCheck.getSelectedIndex()==4)
        {
                  
        }
       }
       catch(Exception ex)
       {
           Logger.getLogger(MainWindowIfc.class.getName()).log(Level.SEVERE, null, ex);
       }
       JTable tab;
	JScrollPane sp;
	Vector content = new Vector();
	Vector header = new Vector();
       
	JPanel p1;
	JLabel l1;
         p1 = new JPanel();
         p1.setBounds(0,150,100,100);
		p1.setLayout(null);
                p1.setBackground(Color.LIGHT_GRAY);
		p1.setSize(800,400);
		l1 = new JLabel("Validation Summary");
		l1.setBounds(300,10, 200, 20);
		l1.setFont(new Font("Comic Sans Ms",Font.BOLD,14));
                //l1.setForeground(Color.WHITE);
		p1.add(l1);
                Connect c=new Connect();
                c.getReport();
        try {
            rs=c.DqlStatement();
            mt=rs.getMetaData();
            
            int count = mt.getColumnCount();
			for (int i = 1; i <= count; i++)
			{
				header.addElement(mt.getColumnName(i));
			}
				while (rs.next())
				{
					Vector row = new Vector(count);
					for (int i = 1; i <= count; i++)
					{
						row.addElement(rs.getObject(i));
					}
					content.addElement(row);
				}
                                
                                tab = new JTable(content,header);
		tab.setBackground(Color.BLUE);
		tab.setColumnSelectionAllowed(false);
		tab.setAutoscrolls(true);
		tab.setGridColor(Color.BLUE);
		tab.setFont(new Font("Monotype Corsiva", Font.PLAIN,12));
		tab.setForeground(Color.WHITE);
		

		tab.setCursor(Cursor.getSystemCustomCursor("TEXT_CURSOR"));
                tab.enable(false);
		TableColumn col;
		for (int i = 0; i < tab.getColumnCount(); i++)
		{
			col = tab.getColumnModel().getColumn(i);
                        col.sizeWidthToFit();
                        
		}
		sp = new JScrollPane(tab);
		
		sp.setBounds(200,50,350,170);
		
		sp.setAutoscrolls(true);
		sp.setVisible(true);
		p1.add(sp);
		this.add(p1);
		p1.setBackground(new Color(204,204,204));
		this.setVisible(true);
        }
        catch(Exception ex)
        {
            
        }
                
                
    }//GEN-LAST:event_validatebuttonActionPerformed

    private void btnexit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexit1ActionPerformed
      if(JOptionPane.showConfirmDialog(this,"Do u Want to Exit this Application")==JOptionPane.OK_OPTION)
        {
            this.setVisible(false);
        }   // TODO add your handling code here:
    }//GEN-LAST:event_btnexit1ActionPerformed

    private void drpCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drpCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drpCheckActionPerformed

    private void drpStoreyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_drpStoreyItemStateChanged
        if(drpCheck.getSelectedIndex()==0)
        {
            status.setText("Status : Check not Selected");
        }
        else
        {
            if(drpStorey.getSelectedIndex()==0)
            {
                status.setText("Status : Storey not Selected");
            }
            else
            {
                status.setText("Status : Press Validate Button to proceed");
            }
             
        }
    }//GEN-LAST:event_drpStoreyItemStateChanged

    private void drpStoreyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drpStoreyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drpStoreyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit1;
    private javax.swing.JComboBox drpCheck;
    private javax.swing.JComboBox drpStorey;
    private javax.swing.JLabel status;
    private javax.swing.JLabel txtStorey;
    private javax.swing.JButton validatebutton;
    private javax.swing.JLabel validationlabel;
    // End of variables declaration//GEN-END:variables
}
