/* Generated By: IFC Tools Project EXPRESS TO JAVA COMPILER: Do not edit this file!! */
package ifc2x3javatoolbox.ifc2x3tc1;

public class IfcFontStyle extends STRING implements TypeInterface
{
	/**
 * The default constructor for the type object IfcFontStyle.
**/
	public IfcFontStyle(){super();}

	/**
 * Constructs a new IfcFontStyle type object using the given parameter.
	 * @param value the value
	**/
	public IfcFontStyle(STRING value)
	{
		this.setValue(value);
	}
	/**

	public IfcFontStyle(String value, boolean isDecoded)
	{
		super(value, isDecoded);
	}
/**
 * This method sets the value of this type object.

 * The value to set must an instance of STRING
 * @param value the value to set
**/	public void setValue(Object value)
	{
	super.setValue((STRING)value);
	}	/**
	 * This method clones the object (deep cloning).
	 *
	 * @return the cloned object
	**/
	public Object clone()
	{		IfcFontStyle fcFontStyle = new IfcFontStyle();
		fcFontStyle.setValue(super.clone());
		return fcFontStyle;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	public String getStepParameter(boolean isSelectType)
	{
		if(isSelectType) return new String("IFCFONTSTYLE("+super.getStepParameter(false)+")");
		else return super.getStepParameter(false);
	}


}
